<?php

namespace BgcwPro\BulkGeneration;

use Bgcw\GiftCard\CodeGenerator;
use Bgcw\GiftCard\Repository;
use Bgcw\GiftCard\TransactionRepository;

defined( 'ABSPATH' ) || exit;

class Generator {

	/**
	 * Initialize hooks.
	 */
	public static function init() {
		add_action( 'wp_ajax_bgcw_pro_bulk_generate', [ __CLASS__, 'ajax_bulk_generate' ] );
		add_action( 'wp_ajax_bgcw_pro_bulk_progress', [ __CLASS__, 'ajax_bulk_progress' ] );
	}

	/**
	 * AJAX handler: bulk-generate gift cards.
	 */
	public static function ajax_bulk_generate() {
		check_ajax_referer( 'bgcw_pro_admin', 'nonce' );

		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_send_json_error(
				[ 'message' => __( 'You do not have permission to perform this action.', 'beltoft-gift-cards-for-woocommerce-pro' ) ],
				403
			);
		}

		$quantity        = isset( $_POST['quantity'] ) ? absint( $_POST['quantity'] ) : 0;
		$amount          = isset( $_POST['amount'] ) ? (float) $_POST['amount'] : 0;
		$prefix          = isset( $_POST['prefix'] ) ? sanitize_text_field( wp_unslash( $_POST['prefix'] ) ) : '';
		$expiry_days     = isset( $_POST['expiry_days'] ) ? absint( $_POST['expiry_days'] ) : 0;
		$recipient_email = isset( $_POST['recipient_email'] ) ? sanitize_email( wp_unslash( $_POST['recipient_email'] ) ) : '';
		$recipient_name  = isset( $_POST['recipient_name'] ) ? sanitize_text_field( wp_unslash( $_POST['recipient_name'] ) ) : '';

		// Validate quantity: 1-500.
		if ( $quantity < 1 || $quantity > 500 ) {
			wp_send_json_error(
				[ 'message' => __( 'Quantity must be between 1 and 500.', 'beltoft-gift-cards-for-woocommerce-pro' ) ]
			);
		}

		// Validate amount: must be positive.
		if ( $amount <= 0 ) {
			wp_send_json_error(
				[ 'message' => __( 'Amount must be greater than zero.', 'beltoft-gift-cards-for-woocommerce-pro' ) ]
			);
		}

		// Store progress transients for polling.
		set_transient( 'bgcw_pro_bulk_total', $quantity, HOUR_IN_SECONDS );
		set_transient( 'bgcw_pro_bulk_progress', 0, HOUR_IN_SECONDS );

		// Temporarily override code prefix if a custom one is provided.
		$has_prefix = ! empty( $prefix );
		if ( $has_prefix ) {
			add_filter( 'option_bgcw_options', function ( $opts ) use ( $prefix ) {
				if ( is_array( $opts ) ) {
					$opts['code_prefix'] = $prefix;
				}
				return $opts;
			} );
			\Bgcw\Support\Options::invalidate_cache();
		}

		$expires_at = $expiry_days > 0
			? gmdate( 'Y-m-d H:i:s', time() + ( $expiry_days * DAY_IN_SECONDS ) )
			: null;

		$created = 0;

		for ( $i = 0; $i < $quantity; $i++ ) {
			$code = CodeGenerator::generate();

			$gc_id = Repository::insert( [
				'code'            => $code,
				'initial_amount'  => $amount,
				'balance'         => $amount,
				'currency'        => get_woocommerce_currency(),
				'sender_name'     => '',
				'sender_email'    => '',
				'recipient_name'  => $recipient_name,
				'recipient_email' => $recipient_email,
				'message'         => '',
				'order_id'        => null,
				'customer_id'     => null,
				'status'          => 'active',
				'expires_at'      => $expires_at,
			] );

			if ( $gc_id ) {
				TransactionRepository::insert( [
					'gift_card_id'  => $gc_id,
					'type'          => 'credit',
					'amount'        => $amount,
					'balance_after' => $amount,
					'note'          => __( 'Bulk generated by admin', 'beltoft-gift-cards-for-woocommerce-pro' ),
				] );

				if ( ! empty( $recipient_email ) ) {
					/**
					 * Fire the gift card created action to trigger email delivery.
					 *
					 * @param int  $gc_id Gift card ID.
					 * @param null $order No order for bulk-generated cards.
					 */
					do_action( 'bgcw_gift_card_created', $gc_id, null );
				}

				++$created;
			}

			set_transient( 'bgcw_pro_bulk_progress', $created, HOUR_IN_SECONDS );
		}

		// Restore original prefix.
		if ( $has_prefix ) {
			\Bgcw\Support\Options::invalidate_cache();
		}

		// Clean up transients.
		delete_transient( 'bgcw_pro_bulk_total' );
		delete_transient( 'bgcw_pro_bulk_progress' );

		wp_send_json_success( [
			'created' => $created,
			/* translators: %d: number of gift cards generated */
			'message' => sprintf( __( '%d gift card(s) generated successfully.', 'beltoft-gift-cards-for-woocommerce-pro' ), $created ),
		] );
	}

	/**
	 * AJAX handler: poll bulk generation progress.
	 */
	public static function ajax_bulk_progress() {
		check_ajax_referer( 'bgcw_pro_admin', 'nonce' );

		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_send_json_error(
				[ 'message' => __( 'You do not have permission to perform this action.', 'beltoft-gift-cards-for-woocommerce-pro' ) ],
				403
			);
		}

		$total    = (int) get_transient( 'bgcw_pro_bulk_total' );
		$progress = (int) get_transient( 'bgcw_pro_bulk_progress' );

		wp_send_json_success( [
			'total'    => $total,
			'progress' => $progress,
		] );
	}
}
